{
 "title": "报警",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "AlarmFilter",
    "label": "报警过滤器",
    "query": "%,AAlarm,Fur,Con,Rinse,Pick,Takeup,Fur%AA,Con%AA,Rinse%AA,Pick%AA,Takeup%AA,Fur%AA,Fur%DA,Con%DA,Rinse%DA,Pick%DA,Takeup%DA,Fur%DA,DAlarm"
   },
   {
    "name": "ShortCut",
    "label": "设备名",
    "query": "SELECT DISTINCT  DeviceName  FROM [dbo].[Diagnostic]"
   }
  ]
 },
 "panels": [
  {
   "title": "各模块报警次数统计",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  GroupPath = \r\n  CASE \r\n    WHEN GroupPath ='' THEN 'System'\r\n    ELSE GroupPath\r\n  END\r\n  ,count(EventAssociationID) as Alarmcount\r\nFROM AllEvent\r\nWHERE \r\n  Active = 1\r\n  and $__timeFilter(EventTimeStamp)\r\nGROUP BY GroupPath\r\nORDER BY Alarmcount DESC"
    }
   ]
  },
  {
   "title": "当前报警",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT TOP 15 [SourceName]\r\n      ,[EventTimeStamp]\r\n      ,[Severity]\r\n      ,[Message]\r\n      ,[AlarmClass]\r\n      ,[InputValue]\r\n      ,[LimitValue]\r\n      ,[UserComment]\r\n      ,[Tag1Value]\r\n      ,[Tag2Value]\r\n      ,[Tag3Value]\r\n      ,[Tag4Value]\r\n      ,[GroupPath]\r\nFROM AllEvent\r\nWHERE \r\n  Active = 1\r\n  and $__timeFilter(EventTimeStamp)\r\nORDER BY EventTimeStamp DESC"
    }
   ]
  },
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "报警持续时间排名（含过滤器 $AlarmFilter）",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "DECLARE\t@return_value int\r\nDECLARE @start datetime\r\nDECLARE @end datetime\r\nDECLARE @now datetime\r\nset @start = $__timeFrom();\r\nset @end = $__timeTo();\r\nset @now = getdate();\r\n\r\ncreate table #temp (\t\t\r\n\tActiveTime [datetime2](7) NULL,\r\n\tInactiveTime [datetime2](7) NULL,\r\n\tAckedTime [datetime2](7) NULL, \r\n\tAlarm [nvarchar](512),\r\n\t[Severity] [int] NULL,\r\n\t[Priority] [int] NULL,\r\n\t[Tag1Value] [nvarchar](128) NULL,\r\n\t[Tag2Value] [nvarchar](128) NULL,\r\n\t[Tag3Value] [nvarchar](128) NULL,\r\n\t[Tag4Value] [nvarchar](128) NULL,\r\n\tDuration [int] NULL,\r\n\t[Message] [nvarchar](512) NULL,\r\n\tSuppressedTime [datetime2](7) NULL,\r\n\tDisabledTime [datetime2](7) NULL,\r\n\t[InputValue] [float] NULL,\r\n\t[LimitValue] [float] NULL, \r\n\tShelvedTime [datetime2](7) NULL,\r\n\tAlarmClass [nvarchar](1000) NULL,\r\n\tEventAssociationID [uniqueidentifier] NULL,\r\n\tServerName[nvarchar](50) NULL,\r\n\tSource [nvarchar](512) NULL)\r\n\r\nINSERT INTO #temp\r\nEXEC\t [dbo].[vpSSRSGetAllEventsInTimePeriod]\r\n\t\t@from_dt = @start,\r\n\t\t@to_dt = @end,\r\n\t\t@alarm = N'$AlarmFilter',\r\n\t\t@ServerName = N'FactoryTalk Linx',\r\n\t\t@LocalTime = @now,\r\n\t\t@TopicName = N'CookieLine',\r\n\t\t@StaleDays = 0\r\nSELECT TOP 5 Alarm,sum(Duration) as SumDuration FROM #temp GROUP BY Alarm ORDER BY SumDuration DESC\r\n--DO NOT FORGET TO DROP THE TEMPLATE TABLE\r\nDROP TABLE #Temp\r\n--SELECT\t'Return Value' = @return_value\r\n"
    }
   ]
  },
  {
   "title": "报警严重性分析（含过滤器 $AlarmFilter）",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sub.SeverityName,Sum(sub.Counter) \r\nFROM\r\n  (SELECT \r\n\t\tCASE \r\n\t\t\tWHEN Severity between 1 and 250 THEN  'Low'\r\n\t\t\tWHEN Severity between 251 and 500  THEN 'Medium'\r\n\t\t\tWHEN Severity between 501 and 750  THEN 'High'\r\n\t\t\tWHEN Severity between 751 and 1000  THEN  'Urgent'\r\n\t\t\tEND AS SeverityName,\r\n\t\tcount(EventAssociationID) AS Counter  \r\nFROM Allevent \r\nWHERE \r\n  (Active = 1 or EffDisabled =0 or Disabled =0 or Suppressed = 0 or Shelved =0)\r\n  and $__timeFilter(EventTimeStamp)\r\n  and SourceName like ('%' + '$AlarmFilter' + '%')\r\nGROUP BY Severity) as sub \r\nGROUP BY sub.SeverityName"
    }
   ]
  },
  {
   "title": "报警类别分析（含报警过滤器 $AlarmFilter）",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n\t\tAlarmClass,\r\n\t\tcount(EventAssociationID) AS Counter  \r\nFROM Allevent \r\nWHERE \r\n  (Active = 1 or EffDisabled =0 or Disabled =0 or Suppressed = 0 or Shelved =0)\r\n  and $__timeFilter(EventTimeStamp)\r\n  and SourceName like ('%' + '$AlarmFilter' + '%')\r\nGROUP BY AlarmClass"
    }
   ]
  },
  {
   "title": "过去一周一直持续的且无人响应的报警",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "rawSql": "DECLARE @start datetime\r\nDECLARE @end datetime\r\nDECLARE @now datetime\r\nset @start = $__timeFrom();\r\nset @end = $__timeTo();\r\nset @now = getdate();\r\n\r\n\r\ncreate table #temp4 (\t\t\r\n\tActiveTime [datetime2](7) NULL,\r\n\tInactiveTime [datetime2](7) NULL,\r\n\tAlarm [nvarchar](512),\r\n\tEventAssociationID [uniqueidentifier] NULL,\r\n\tSourceLong [nvarchar](512) NULL,\r\n\t)\r\n\r\n--GROUP BY SourceName\r\n\r\nINSERT INTO #temp4\r\n\r\n\r\nEXEC [dbo].[vpSSRSGetAllEventsInTimePeriod_Stale]\r\n\t\t@from_dt = @start,\r\n\t\t@to_dt = @end,\r\n\t\t@alarm = N'',\r\n\t\t@ServerName = N'FactoryTalk Linx',\r\n\t\t@LocalTime = @now,\r\n\t\t@TopicName = N'Myself',\r\n\t\t@StaleDays = 7\r\nselect Top 10 ActiveTime, Alarm, SourceLong from #temp4 order by ActiveTime desc\r\nDrop table #temp4"
    }
   ]
  },
  { "title": "特殊报警列表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "被禁用的报警",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "DECLARE\t@return_value int\r\nDECLARE @start datetime\r\nDECLARE @end datetime\r\nDECLARE @now datetime\r\nset @start = $__timeFrom();\r\nset @end = $__timeTo()\r\nset @now = getdate();\r\n\r\n\r\ncreate table #temp3 (\t\t\r\n\tDisabledTime [datetime2](7) NULL,\r\n\tEnabledTime [datetime2](7) NULL,\r\n\tAlarm [nvarchar](512),\r\n\t[Severity] [int] NULL,\r\n\t[Priority] [int] NULL,\r\n\t[Tag1Value] [nvarchar](128) NULL,\r\n\t[Tag2Value] [nvarchar](128) NULL,\r\n\t[Tag3Value] [nvarchar](128) NULL,\r\n\t[Tag4Value] [nvarchar](128) NULL,\r\n\t[Message] [nvarchar](512) NULL,\r\n\t[InputValue] [float] NULL,\r\n\t[LimitValue] [float] NULL, \r\n\tAlarmClass [nvarchar](1000) NULL,\r\n\tDisabledDuration [int] NULL,\r\n\tSourceLong [nvarchar](512) NULL,\r\n\tSourceShort [nvarchar](512) NULL,\r\n\tEventAssociationID [uniqueidentifier] NULL\r\n\t)\r\n\r\n--GROUP BY SourceName\r\n\r\nINSERT INTO #temp3\r\nEXEC\t [dbo].[vpSSRSDisabledAlarms]\r\n\t\t@from_dt = @start,\r\n\t\t@to_dt = @end,\r\n\t\t@alarm = N'$AlarmFilter',\r\n\t\t@ServerName = N'FactoryTalk Linx',\r\n\t\t@LocalTime = @now,\r\n\t\t@TopicName = N'CookieLine'\r\nselect top 5 * from #temp3 order by DisabledDuration desc\r\nDrop table #temp3"
    }
   ]
  },
  {
   "title": "被压制的报警",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "DECLARE\t@return_value int\r\nDECLARE @start datetime\r\nDECLARE @end datetime\r\nDECLARE @now datetime\r\nset @start = $__timeFrom();\r\nset @end = $__timeTo();\r\nset @now = getdate();\r\n\r\n\r\ncreate table #Temp1 (\t\t\r\n\tSuppressedTime [datetime2](7) NULL,\r\n\tUnsuppressedTime [datetime2](7) NULL,\r\n\tAlarm [nvarchar](512),\r\n\t[Severity] [int] NULL,\r\n\t[Priority] [int] NULL,\r\n\t[Tag1Value] [nvarchar](128) NULL,\r\n\t[Tag2Value] [nvarchar](128) NULL,\r\n\t[Tag3Value] [nvarchar](128) NULL,\r\n\t[Tag4Value] [nvarchar](128) NULL,\r\n\t[Message] [nvarchar](512) NULL,\r\n\t[InputValue] [float] NULL,\r\n\t[LimitValue] [float] NULL, \r\n\tAlarmClass [nvarchar](1000) NULL,\r\n\tSuppressedDuration [int] NULL,\r\n\tSourceLong [nvarchar](512) NULL,\r\n\tSourceShort [nvarchar](512) NULL,\r\n\tEventAssociationID [uniqueidentifier] NULL)\r\n\r\n--GROUP BY SourceName\r\n\r\nINSERT INTO #Temp1\r\nEXEC\t [dbo].[vpSSRSSuppressedAlarms]\r\n\t\t@from_dt = @start,\r\n\t\t@to_dt = @end,\r\n\t\t@alarm = N'$AlarmFilter',\r\n\t\t@ServerName = N'FactoryTalk Linx',\r\n\t\t@LocalTime = @now,\r\n\t\t@TopicName = N'CookieLine'\r\nselect top 5 * from #Temp1 order by SuppressedTime desc\r\n\r\n--DO NOT FORGET TO DROP THE TEMPLATE TABLE\r\nDROP TABLE #Temp1\r\n--SELECT\t'Return Value' = @return_value\r\n"
    }
   ]
  },
  {
   "title": "被忽略的报警",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "DECLARE\t@return_value int\r\nDECLARE @start datetime\r\nDECLARE @end datetime\r\nDECLARE @now datetime\r\nset @start = $__timeFrom();\r\nset @end = $__timeTo();\r\nset @now = getdate();\r\n\r\n\r\ncreate table #temp2 (\t\t\r\n\tShelved [datetime2](7) NULL,\r\n\tUnShelvedTime [datetime2](7) NULL,\r\n\tAutoUnshelveTime [datetime2](7) NULL,\r\n\tAlarm [nvarchar](512),\r\n\t[Severity] [int] NULL,\r\n\t[Priority] [int] NULL,\r\n\t[Tag1Value] [nvarchar](128) NULL,\r\n\t[Tag2Value] [nvarchar](128) NULL,\r\n\t[Tag3Value] [nvarchar](128) NULL,\r\n\t[Tag4Value] [nvarchar](128) NULL,\r\n\t[Message] [nvarchar](512) NULL,\r\n\t[InputValue] [float] NULL,\r\n\t[LimitValue] [float] NULL, \r\n\tAlarmClass [nvarchar](1000) NULL,\r\n\tShelvedDuration [int] NULL,\r\n\tSourceLong [nvarchar](512) NULL,\r\n\tSourceShort [nvarchar](512) NULL,\r\n\tEventAssociationID [uniqueidentifier] NULL\r\n\t)\r\n\r\n--GROUP BY SourceName\r\n\r\nINSERT INTO #temp2\r\nEXEC\t [dbo].[vpSSRSShelvedAlarms]\r\n\t\t@from_dt = @start,\r\n\t\t@to_dt = @end,\r\n\t\t@alarm = N'$AlarmFilter',\r\n\t\t@ServerName = N'FactoryTalk Linx',\r\n\t\t@LocalTime = @now,\r\n\t\t@TopicName = N'CookieLine'\r\nselect top 5 * from #temp2 order by ShelvedDuration desc\r\nDrop table #temp2"
    }
   ]
  },
  { "title": "Diagnostic Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Diagnostic Summary",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT TOP 15\n  [DeviceName]\n  ,[Message]\n  ,[EventTimeStamp]\n  FROM [FTAE].[dbo].[Diagnostic]\n  WHERE State = 1 and  [DeviceName] IN ( $ShortCut) and $__timeFilter(EventTimeStamp)\n  ORDER BY EventTimeStamp desc"
    }
   ]
  }
 ]
}