{
 "title": "集团总览",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ID", "query": "SELECT id FROM SimulateMap" }
  ]
 },
 "panels": [
  {
   "title": "中国区工厂OEE/产量总览",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  City,Latitude,Longitude,(Availability/100)*(Quality/100)*(performance/100) as OEE, Volume,timestamp,id\nFROM\n  [dbo].[SimulateMap]"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  City\nFROM\n  [dbo].[SimulateMap]\nWHERE\n  id = $ID\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "options": {
    "content": "<font size=\"12\" color=\"F0F8FF\"></font>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  (Availability*Quality*performance)/10000 as OEE\nFROM\n  [dbo].[SimulateMap]\nWHERE\n  id = $ID\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 1, "x": 12, "y": 2 },
   "options": {
    "content": "<font size=\"4\">安全</font>\r\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SafetyDayLost,Training,SafetyRunningDays\nFROM\n  SimulateMap\nWHERE\n  id = $ID"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 12, "y": 5 },
   "options": {
    "content": "<font size=\"4\">OEE</font>\r\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  City\nFROM\n  [dbo].[SimulateMap]\nWHERE\n  id = $ID\n"
    }
   ]
  },
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  (Availability*Quality*performance)/10000 as OEE\nFROM\n  [dbo].[SimulateMap]\nWHERE\n  id = $ID\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 17, "y": 5 },
   "options": {
    "content": "<font size=\"12\" color=\"F0F8FF\"></font>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  (Availability*Quality*performance)/10000 as OEE\nFROM\n  [dbo].[SimulateMap]\nWHERE\n  id = $ID\n"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  Availability,Quality,performance\nFROM\n  [dbo].[SimulateMap]\nWHERE\n  id = $ID\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 1, "x": 17, "y": 7 },
   "options": {
    "content": "<font size=\"12\" color=\"F0F8FF\">=</font>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  (Availability*Quality*performance)/10000 as OEE\nFROM\n  [dbo].[SimulateMap]\nWHERE\n  id = $ID\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 1, "x": 12, "y": 11 },
   "options": {
    "content": "<font size=\"6\">能耗</font>\r\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  City\nFROM\n  [dbo].[SimulateMap]\nWHERE\n  id = $ID\n"
    }
   ]
  },
  {
   "title": "电能消耗",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  PowerConsumption\nFROM\n  [dbo].[SimulateMap]\nWHERE\n  id = $ID\n\n"
    }
   ]
  },
  {
   "title": "天然气消耗",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  GasConsumption\nFROM\n  [dbo].[SimulateMap]\nWHERE\n  id = $ID\n\n"
    }
   ]
  },
  {
   "title": "电能曲线",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"ISC1\")\r\n  |> range(start: -1d, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerConsumption\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "天然气曲线",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "query": "from(bucket: \"ISC1\")\r\n  |> range(start: -1d, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"GasConsumption\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 24 },
   "targets": [
    {}
   ]
  }
 ]
}