{
 "title": "PLC/IOT硬件信息",
 "description": "Dashboard for displaying basic host metrics collected by telegraf and stored into the InfluxDB 2.0. Metrics are fetched by flux.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "influxdb" },
   { "name": "bucket", "label": "时序数据库", "query": "ISC1" },
   {
    "name": "host",
    "label": "主机名",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"host\")"
   },
   {
    "name": "inter",
    "label": "间隔",
    "query": "1s,5s,10s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d,60d,90d"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"${bucket}\", tag: \"cpu\")"
   },
   {
    "name": "disk",
    "label": "硬盘",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"${bucket}\", tag: \"device\")"
   },
   {
    "name": "ShortCut",
    "label": "设备名",
    "query": "  select distinct DeviceName from [dbo].[Diagnostic]"
   }
  ]
 },
 "panels": [
  { "title": "PLC使用概况：", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"../public/img/rockwell/Rockwell.png\"/>\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "CPU实时温度：",
     "nodePath": {
      "browsePath": [
       { "name": "FactoryTalkLinxGateway", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "CookieLine", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "Online", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "CPUTemperature", "namespaceUrl": "FTLGW_Server_Namespace" }
      ],
      "node": {
       "browseName": { "name": "CPUTemperature", "namespaceUrl": "FTLGW_Server_Namespace" },
       "displayName": "CPUTemperature",
       "isForward": true,
       "nodeClass": 2,
       "nodeId": "{\"namespaceUrl\":\"FTLGW_Server_Namespace\",\"id\":\"ns=2;s=[CookieLine]CPUTemperature\"}",
       "typeId": "Numeric"
      }
     },
     "readType": "ReadNode"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 5, "y": 1 },
   "targets": [
    {
     "alias": "CPU温度：",
     "nodePath": {
      "browsePath": [
       { "name": "FactoryTalkLinxGateway", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "CookieLine", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "Online", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "CPUTemperatureOK", "namespaceUrl": "FTLGW_Server_Namespace" }
      ],
      "node": {
       "browseName": { "name": "CPUTemperatureOK", "namespaceUrl": "FTLGW_Server_Namespace" },
       "displayName": "CPUTemperatureOK",
       "isForward": true,
       "nodeClass": 2,
       "nodeId": "{\"namespaceUrl\":\"FTLGW_Server_Namespace\",\"id\":\"ns=2;s=[CookieLine]CPUTemperatureOK\"}",
       "typeId": "Numeric"
      }
     },
     "readType": "ReadNode"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PLC\")\r\n  |> filter(fn: (r) => r[\"Part\"] == \"PLC_Utility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CpuIdle\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: 100 - r._value})) \r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "系统任务CPU使用率详情",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PLC\")\r\n  |> filter(fn: (r) => r[\"Part\"] == \"PLC_Utility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CpuClass3\" or r[\"_field\"] == \"CpuClass1\" or r[\"_field\"] == \"CpuControl\" or r[\"_field\"] == \"CpuControlMotion\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PLC各任务完成时间占比",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PLC\")\r\n  |> filter(fn: (r) => r[\"Part\"] == \"PLC_Utility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TaskAlarmEmulate\" or r[\"_field\"] == \"TaskMotion\" or r[\"_field\"] == \"TaskNew\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> last()\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  \r\n  |> drop(columns: [\"_measurement\",\"_start\",\"_stop\",\"_time\",\"host\",\"Part\"])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 3 },
   "options": {
    "content": "<img src=\"../public/img/rockwell/5480_1.png\"/>\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "alias": "风扇1速度：",
     "nodePath": {
      "browsePath": [
       { "name": "FactoryTalkLinxGateway", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "CookieLine", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "Online", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "Fan1Speed", "namespaceUrl": "FTLGW_Server_Namespace" }
      ],
      "node": {
       "browseName": { "name": "Fan1Speed", "namespaceUrl": "FTLGW_Server_Namespace" },
       "displayName": "Fan1Speed",
       "isForward": true,
       "nodeClass": 2,
       "nodeId": "{\"namespaceUrl\":\"FTLGW_Server_Namespace\",\"id\":\"ns=2;s=[CookieLine]Fan1Speed\"}",
       "typeId": "Numeric"
      }
     },
     "readType": "ReadNode"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "风扇1：",
     "nodePath": {
      "browsePath": [
       { "name": "FactoryTalkLinxGateway", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "CookieLine", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "Online", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "Fan1OK", "namespaceUrl": "FTLGW_Server_Namespace" }
      ],
      "node": {
       "browseName": { "name": "Fan1OK", "namespaceUrl": "FTLGW_Server_Namespace" },
       "displayName": "Fan1OK",
       "isForward": true,
       "nodeClass": 2,
       "nodeId": "{\"namespaceUrl\":\"FTLGW_Server_Namespace\",\"id\":\"ns=2;s=[CookieLine]Fan1OK\"}",
       "typeId": "Numeric"
      }
     },
     "readType": "ReadNode"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "alias": "风扇2速度：",
     "nodePath": {
      "browsePath": [
       { "name": "FactoryTalkLinxGateway", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "CookieLine", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "Online", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "Fan2OK", "namespaceUrl": "FTLGW_Server_Namespace" }
      ],
      "node": {
       "browseName": { "name": "Fan2OK", "namespaceUrl": "FTLGW_Server_Namespace" },
       "displayName": "Fan2OK",
       "isForward": true,
       "nodeClass": 2,
       "nodeId": "{\"namespaceUrl\":\"FTLGW_Server_Namespace\",\"id\":\"ns=2;s=[CookieLine]Fan2OK\"}",
       "typeId": "Numeric"
      }
     },
     "readType": "ReadNode"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "风扇2：",
     "nodePath": {
      "browsePath": [
       { "name": "FactoryTalkLinxGateway", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "CookieLine", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "Online", "namespaceUrl": "FTLGW_Server_Namespace" },
       { "name": "Fan2OK", "namespaceUrl": "FTLGW_Server_Namespace" }
      ],
      "node": {
       "browseName": { "name": "Fan2OK", "namespaceUrl": "FTLGW_Server_Namespace" },
       "displayName": "Fan2OK",
       "isForward": true,
       "nodeClass": 2,
       "nodeId": "{\"namespaceUrl\":\"FTLGW_Server_Namespace\",\"id\":\"ns=2;s=[CookieLine]Fan2OK\"}",
       "typeId": "Numeric"
      }
     },
     "readType": "ReadNode"
    }
   ]
  },
  {
   "title": "系统任务CPU使用率历史记录",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PLC\")\r\n  |> filter(fn: (r) => r[\"Part\"] == \"PLC_Utility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CpuClass3\" or r[\"_field\"] == \"CpuClass1\" or r[\"_field\"] == \"CpuControl\" or r[\"_field\"] == \"CpuControlMotion\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "L46ERM 定时任务执行占比历史曲线",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PLC\")\r\n  |> filter(fn: (r) => r[\"Part\"] == \"PLC_Utility\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TaskAlarmEmulate\" or r[\"_field\"] == \"TaskMotion\" or r[\"_field\"] == \"TaskNew\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Windows IoT系统使用概况：",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU占用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\" and  r[\"_field\"] == \"usage_idle\" and r[\"cpu\"] == \"cpu-total\" and r[\"host\"] == \"DESKTOP-32OGS9I\" )\n  |> last()\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "内寸占用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) =>  r.host == \"${host}\")\n  |> last()\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "虚拟内存占用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"swap\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) =>  r.host == \"${host}\")\n  |> last()\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "硬盘读写等待",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_iowait\")\n  |> filter(fn: (r) =>  r.host == \"${host}\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> last()\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "内存，CPU，硬盘使用历史",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "import \"experimental\"\nt1 = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\nt3 = from(bucket: \"ISC1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |>  map(fn: (r) => ({r with _value:60000000000.00 - r._value}))\nt2 = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\" and r[\"cpu\"] == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with _value:100.0 - r._value}))\n\n  union(tables: [t1, t2, t3])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "硬盘I/O响应时间历史",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "//SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *\n\nfrom(bucket:  \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r.host == \"${host}\" and r.name =~ /$disk$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"read_time\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "//SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *\n\nfrom(bucket:  \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r.host == \"${host}\" and r.name =~ /$disk$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"write_time\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "虚拟内存使用历史",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "swap_in",
     "query": "//SELECT mean(free) as \"free\", mean(used) as \"used\", mean(total) as \"total\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc\n\nfrom(bucket:  \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"swap\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free\" or r[\"_field\"] == \"used\" or r[\"_field\"] == \"total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "硬盘I/O读写字节数历史",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "//SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *\n\nfrom(bucket:  \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r.host == \"${host}\" and r.name =~ /$disk$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "//SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *\n\nfrom(bucket:  \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r.host == \"${host}\" and r.name =~ /$disk$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"write_bytes\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}