{
 "title": "工艺",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "GroupPath",
    "label": "设备模块",
    "query": "Furnace,Conditioner,Takeup,Picking,Rinsing"
   },
   {
    "name": "ShortCut",
    "label": "设备名",
    "query": "  select distinct DeviceName from [dbo].[Diagnostic]"
   }
  ]
 },
 "panels": [
  {
   "title": "区域 $GroupPath 报警次数排名",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT TOP 7\r\n  SubString(SourceName,CHARINDEX('@',SourceName,0)+1,Len(SourceName))\r\n  ,count(EventAssociationID) as Alarmcount\r\nFROM AllEvent\r\nWHERE \r\n  Active = 1 \r\n  and GroupPath = '$GroupPath'\r\n  and $__timeFilter(EventTimeStamp)\r\nGROUP BY SourceName\r\nORDER BY Alarmcount DESC"
    }
   ]
  },
  {
   "title": "$GroupPath 过程变量当前值",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ISC1\")\r\n  |> range(start: -1h, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Machines\")\r\n  |> filter(fn: (r) => r[\"Part\"] == \"${GroupPath}\")\r\n  |> filter(fn: (r) => r[\"_field\"] != \"Quality\")\r\n  |> last()\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n "
    }
   ]
  },
  {
   "title": "$GroupPath 工艺变量历史曲线",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"ISC1\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Machines\")\r\n  |> filter(fn: (r) => r[\"Part\"] == \"${GroupPath}\")\r\n  |> filter(fn: (r) => r[\"_field\"] != \"Quality\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "诊断信息汇总",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT \n  [DeviceName]\n  ,[Message]\n  ,[EventTimeStamp]\n  FROM [dbo].[Diagnostic]\n  WHERE State = 1 and  [DeviceName] IN ( $ShortCut) and $__timeFilter(EventTimeStamp)\n  ORDER BY EventTimeStamp"
    }
   ]
  }
 ]
}