version: '3.9'
services:
  influxdb:
    image: influxdb:2.3.0
    container_name: influxdb2
    restart: always
    volumes:
      - db:/var/lib/influxdb2  #data for influxdb, if you are in Linux system, use the host folder /var/lib/influxdb2 is ok
      - db_cfg:/etc/influxdb2  #Config for influxdb, if you are in Linux system, use the host folder /etc/influxdb2 is ok
    ports:
      - 8086:8086

    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=rockwellautomation
      - DOCKER_INFLUXDB_INIT_ORG=ra
      - DOCKER_INFLUXDB_INIT_BUCKET=ISC1
      - DOCKER_INFLUXDB_INIT_RETENTION=14d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=U0pdAvYrUbJMPvnD8YZjkm9d8KCVHpeBEe1_LiVlQImsr98ERFRrYKge1hsZVeht_VfEAixTkgsAi6B85lax-Q==
    networks:
      bridge:
        ipv4_address: 172.16.0.2
  opcua:
    image: telegraf:1.23.4
    container_name: telegraf
    extra_hosts:
      - "influx:172.16.0.2"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
      - grafana
    networks:
      bridge:
        ipv4_address: 172.16.0.4
  grafana:
    image: grafana/grafana:8.5.21
    container_name: grafana
    restart: always
    user: "0" # needs to be `id -u` // alternatively chown the grafana/data dir to 472:472
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana # data path , if you are in Linux system, use the host folder /var/lib/grafana is ok
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      #- GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=rockwellautomation
      - GF_AUTH_ANONYMOUS_ENABLED=true
    extra_hosts:
      - "influx:172.16.0.2"
    depends_on:
      - influxdb
    networks:
      bridge:
        ipv4_address: 172.16.0.5
  cip:
    image: coabbb/ra:1.0.1
    container_name: mycip
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./Connection.json:/var/lib/Connection.json
    depends_on:
      - influxdb
      - grafana
    extra_hosts:
      - "influx:172.16.0.2"
    networks:
      bridge:
            ipv4_address: 172.16.0.3
networks:
  bridge:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"
volumes:
  db:
  db_cfg:
  grafana_data:
