version: '3.9'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb2
    restart: always
    volumes:
      - db:/var/lib/influxdb2
      - db_cfg:/etc/influxdb2
    ports:
      - 8086:8086

    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=BekaertRockwell
      - DOCKER_INFLUXDB_INIT_ORG=ra
      - DOCKER_INFLUXDB_INIT_BUCKET=test1
      - DOCKER_INFLUXDB_INIT_RETENTION=3d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=U0pdAvYrUbJMPvnD8YZjkm9d8KCVHpeBEe1_LiVlQImsr98ERFRrYKge1hsZVeht_VfEAixTkgsAi6B85lax-Q==
    networks:
      bridge:
        ipv4_address: 172.16.0.2
  cip:
    image: coabbb/ra:test
    container_name: mytest
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    volumes:
      - c:\\C.json:/var/lib/Connection.json
    depends_on:
      - influxdb
    extra_hosts:
      - "influx:172.16.0.2"
    networks:
      bridge:
            ipv4_address: 172.16.0.3
networks:
  bridge:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"
volumes:
  db:
  db_cfg:
