apiVersion: 1

datasources:
  - name: MSSQL
    type: mssql
    uid: my_mssql
    url: 192.168.248.40:1433
    database: AlarmEvent
    user: sa
    jsonData:
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: '123'
  - name: InfluxDB2
    type: influxdb
    access: proxy
    uid: my_influxdb2
    url: http://influx:8086
    secureJsonData:
      token: U0pdAvYrUbJMPvnD8YZjkm9d8KCVHpeBEe1_LiVlQImsr98ERFRrYKge1hsZVeht_VfEAixTkgsAi6B85lax-Q==
    jsonData:
      version: Flux
      organization: ra
      defaultBucket: test1
      tlsSkipVerify: true